-- Create WAITING_LIST table if it doesn't exist
CREATE TABLE IF NOT EXISTS `WAITING_LIST` (
    `ENTRY_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `FULL_NAME` VARCHAR(255) NOT NULL,
    `MOBILE_NUMBER` VARCHAR(20) NOT NULL,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 